fix: Parallel configure failure.
aminya/project_options pull request #217
Opened 2023-05-02 18:44 UTC by Project579

When trying to configure multiple build directories in parallel project_options will try to create a symlink for compile_commands.json; multiple symlinks will be created at the same time with different targets, obviously this fails; Add a way to disable the symlink creation.
This also fixes CMake failing to configure projects with a read-only sources directory.

2023-05-02 20:27 UTC, aminya approved these changes

2023-05-02 20:28 UTC, aminya requested changes
Could you make this feature optional, i.e., add an option for enabling it instead of disabling it?

2023-05-02 22:07 UTC, Project579 commented
@aminya Do you want to make the "compile_commands.json" symlink disabled by default then? In the current version of the PR it stays enabled by default.

2023-05-02 22:20 UTC, aminya commented
> @aminya Do you want to make the "compile_commands.json" symlink disabled by default then? In the current version of the PR it stays enabled by default.

Yeah, it seems it is causing issues as you mentioned. I prefer that make it disabled by default to avoid any problems.

2023-05-03 17:50 UTC, aminya approved these changes

2023-05-03 17:50 UTC, merged