feat: Support the usage of clang-tidy when cross compiling with GCC.
aminya/project_options pull request #224
Opened 2023-05-17 20:43 UTC by Project579

Currently clang-tidy will fail to run if using GCC with a target different from the host, this modification allows us to extract the default target and sysroot from a GCC compiler in order to feed it to clang-tidy.

2023-05-18 21:39 UTC, aminya requested changes
It seems that the MinGW tests are failing on Windows.

2023-06-02 14:58 UTC, Project579 commented
The tests seem to be passing now except for an expired certificate but that's not related to this PR.

2023-06-05 04:00 UTC, aminya approved these changes
Thanks very much! 🎉

2023-06-05 04:03 UTC, aminya commented on src/StaticAnalyzers.cmake
> +    set(CLANG_TIDY_CXX_FLAGS_COMPILER_TARGET "--target=${CLANG_TIDY_CXX_FLAGS_COMPILER_TARGET}")
There is a DetectCompiler module. I am not sure if this part can be simplified using that. In any case, we can probably refactor it into that module can introduce some macros for compiler/target detection.

2023-06-05 04:03 UTC, merged