fix: Disable gcc sanitizer on macos by default
aminya/project_options pull request #255
Opened 2024-03-27 14:28 UTC by FeignClaims

According to [this comment](https://github.com/orgs/Homebrew/discussions/3384#discussioncomment-6264292), gcc now dosen't support libsanitizer on macOS with arm64 and macOS Ventuna or later with x86_64.

2024-04-01 05:50 UTC, aminya requested changes
But this issue didn't happen inside CI. We should be able to reproduce it to disable it?

2024-04-01 05:59 UTC, FeignClaims commented
> But this issue didn't happen inside CI. We should be able to reproduce it to disable it?

The issue happens inside the DynamicProjectOptions.cmake, which sets UBSAN and ASAN for gcc by default (except for windows):

> ```cmake
>   if((CMAKE_CXX_COMPILER_ID MATCHES ".*Clang.*" OR CMAKE_CXX_COMPILER_ID MATCHES ".*GNU.*")
>      AND WIN32
>   )
>    ...
>  else()
>    ...
>  endif()
> ```

So use `dynamic_project_options` instead of `project_options` should trigger the issue, but I failed to figure out how to add such a  test.

2024-04-01 13:04 UTC, FeignClaims commented
Convert to a draft until

- find a way to test this.
- detect MacOS OS version to keep gcc sanitizers enable on x86_64 macOS Monterey or older.

2024-04-16 10:02 UTC, FeignClaims commented
@aminya The issue happened in the new gcc macos-13 [ci](https://github.com/aminya/project_options/actions/runs/8702993820/job/23868245200) as expected.

2024-04-16 11:49 UTC, FeignClaims commented
Ready to merge.

changes:

- Disable gcc sanitizers on x86_64 MacOS 13+ and arm64 MacOS.
- Add tests for this by adding a gcc macos-13 ci run and enabling sanitizers for it. (Sadly, I can only test arm64 MacOS munally as github actions dosen't support it.)
- For consistency, use `detect_sanitizers_support` inside `dynamic_project_options` to detect whether enabling sanitizers or not.

2024-04-16 18:16 UTC, aminya approved these changes

2024-04-16 18:17 UTC, aminya commented
Thanks for the investigation. It would be great if you could create an issue for the upstream so that they can look into the problem.

2024-04-16 18:17 UTC, merged

2024-04-17 00:30 UTC, FeignClaims commented
Although no related issue, it seems that the upstream already knows the issue and chooses not to support this for now (see https://github.com/iains/gcc-darwin-arm64/commit/e722a1f42b28092c9f709a3f758fc4fe57db32b0).